### ISSUE TITLE
try it feature is not visibile

### ISSUE THREAD

**Issue by mkassir95** [Redocly/openapi-starter#57]
try it console feature is not visible 
![image](https://user-images.githubusercontent.com/72728047/163165242-1162f281-8d6c-4b7c-8a78-82f08a345acd.png)

**Comment by skadinna** [comment]
The _Try it_ console is [not supported in Redocly's open source tools](https://redocly.com/docs/api-reference-docs/guides/try-it-console/). It is available only in Redocly Reference and Developer portal products.
